import React from 'react';
import {ArrowRight,CheckCircle2,Coffee,HeartHandshake,Lightbulb,MousePointer2,Sparkles,Users,Workflow,ShieldCheck,BrainCircuit} from 'lucide-react';
import './v3.css';
const weeks=[['1주차','내 일을 골라봐요','매주 반복하는 업무 하나를 골라 어디가 번거로운지 함께 찾아봅니다.',Lightbulb],['2주차','AI와 나눠서 해봐요','AI에게 맡길 일과 내가 직접 판단할 일을 나누고 작은 자동화를 만들어봅니다.',Workflow],['3주차','막히는 곳을 고쳐봐요','일부러 조건을 바꿔보고, 동료와 1:1 피드백으로 실패해도 고칠 수 있게 만듭니다.',HeartHandshake],['4주차','내 결과물로 남겨요','새로운 문제에도 적용해보고 나만의 AI 업무 포트폴리오로 정리합니다.',Sparkles]];
const who=['AI가 좋다는데 어디서부터 시작할지 막막한 분','강의는 많이 봤지만 내 업무에는 못 써본 분','질문하기 눈치 보여 혼자 끙끙대 본 분','퇴직·이직·창업을 준비하며 새로운 무기가 필요한 분'];
const ladder=[
 {lv:'START',title:'회의 후속업무',desc:'회의록에서 할 일·담당자·기한을 찾아 사람이 확인한 뒤 정리합니다.',meta:'60분 · 공통업무',icon:'📝'},
 {lv:'BUILD',title:'영업실적 주간보고',desc:'숫자 기준을 적용해 이상징후를 찾고 AI 초안과 사람 판단을 연결합니다.',meta:'90분 · 데이터',icon:'📊'},
 {lv:'ANALYZE',title:'고객문의·VOC 분석',desc:'많은 의견을 분류하되 민감한 문의와 애매한 사례는 사람에게 넘깁니다.',meta:'90분 · 분류/분석',icon:'💬'},
 {lv:'ARCHITECT',title:'제안서 의사결정 지원',desc:'고객 요구, 과거 자료, 원가 조건이 충돌할 때 근거를 연결하고 사람이 전략을 결정합니다.',meta:'150분 · 기획',icon:'🧩'},
 {lv:'GOVERN',title:'계약·규정 리스크 점검',desc:'계약과 내부 규정을 비교하되 AI가 결론을 단정하지 않고 검토가 필요한 지점을 안전하게 넘깁니다.',meta:'180분 · 리스크',icon:'🛡️'},
 {lv:'STRATEGY',title:'신사업 기회 탐색',desc:'시장·고객·경쟁·내부역량을 연결하고 찬성 근거뿐 아니라 반대 근거까지 검토합니다.',meta:'210분 · 전략',icon:'🧭'},
 {lv:'ORCHESTRATE',title:'경영회의 멀티에이전트 준비',desc:'재무·영업·고객·운영 관점의 분석이 충돌할 때 쟁점을 정리하고 최종 결정은 경영진에게 남깁니다.',meta:'240분 · 고급',icon:'🏢'}
];
export default function LandingV3(){return <div className="v3"><header className="v3nav"><a href="#top" className="v3brand"><span>STA</span><b>S.T.A.크래프트</b></a><nav><a href="#how">배우는 법</a><a href="#challenge">과제</a><a href="#weeks">4주 과정</a><a href="#result">결과물</a></nav><a className="v3mini" href="#start">과제 구경하기</a></header><main id="top">
<section className="v3hero"><div className="v3copy"><div className="v3eyebrow"><Coffee size={17}/> AI가 낯선 경력자를 위한 4주 실전 연습</div><h1>AI를 배우는 대신,<br/><em>내 일을 바꿔봅니다.</em></h1><p className="v3lead">처음에는 회의록 정리처럼 쉬운 일부터 시작합니다.<br/>익숙해지면 보고서, 리스크 점검, 신사업 의사결정까지.<br/><strong>내 경험을 AI와 함께 일하는 방식으로 바꾸는 연습</strong>을 합니다.</p><div className="v3actions"><a href="#challenge" className="v3primary">과제 난이도 보기 <ArrowRight size={18}/></a><a href="?version=2#lab" className="v3secondary">직접 체험하기</a></div><div className="v3trust"><span><CheckCircle2/> 코딩을 몰라도</span><span><CheckCircle2/> 쉬운 과제부터</span><span><CheckCircle2/> 최종 판단은 사람이</span></div></div><div className="v3scene"><div className="bubble one">“AI에게 어디까지 맡겨도 될까요?”</div><div className="bubble two">“그 판단 기준을 직접 설계해보는 겁니다.”</div><div className="desk"><div className="avatar">나</div><div><small>4주 뒤 목표</small><b>AI를 쓰는 사람에서<br/>AI와 일하는 방식을 설계하는 사람으로</b><span>내 경험은 판단 기준이 됩니다 ✓</span></div></div><div className="v3note"><BrainCircuit/> 도구 사용법보다<br/><b>문제를 풀어내는 힘을 연습합니다.</b></div></div></section>
<section className="v3problem"><p>AI 강의를 들었는데도 업무가 그대로라면</p><div><b>“도구”보다 “내 일”을 먼저 봐야 합니다.</b><span>무엇을 넣을까?</span><span>AI가 뭘 할까?</span><span>어디서 사람이 볼까?</span><span>틀리면 어떻게 할까?</span></div><h2>쉬운 문제에서 시작해<br/><em>복잡한 의사결정까지</em> 올라갑니다.</h2></section>
<section id="how" className="v3section"><div className="v3heading"><span>배우는 방법</span><h2>만들고, 깨뜨리고,<br/>다시 고칩니다.</h2><p>정답을 외우는 과정이 아닙니다. 직접 설계한 업무 흐름에 조건을 바꾸고 예외를 넣어보며 스스로 수정할 수 있는지 확인합니다.</p></div><div className="v3three"><article><span>01 · BUILD</span><MousePointer2/><h3>직접 만들어보기</h3><p>내가 아는 업무를 입력·규칙·AI 역할·사람 판단·결과물로 나눠봅니다.</p></article><article><span>02 · BREAK & FIX</span><ShieldCheck/><h3>일부러 깨뜨려보기</h3><p>자료가 빠지거나 기준이 바뀌면 어떻게 될까요? 실패 조건을 넣고 다시 고칩니다.</p></article><article><span>03 · TRANSFER</span><HeartHandshake/><h3>새 문제에 적용하기</h3><p>동료 피드백과 1:1 도움을 받은 뒤 처음 보는 문제에도 같은 사고방식을 적용합니다.</p></article></div></section>
<section id="challenge" className="v3challenges"><div className="v3heading"><span>CHALLENGE LADDER</span><h2>쉬운 과제부터<br/>경영 의사결정까지.</h2><p>모든 과제를 다 할 필요는 없습니다. 현재 수준에서 시작해 한 단계씩 올라갑니다. 아래 과제는 교육모델 검증을 위한 가상 시나리오입니다.</p></div><div className="challengeGrid">{ladder.map((x,i)=><article key={x.title}><div className="challengeTop"><span>{x.icon}</span><b>LEVEL {i+1} · {x.lv}</b></div><h3>{x.title}</h3><p>{x.desc}</p><small>{x.meta}</small>{i>=3&&<em>고도화 과제</em>}</article>)}</div><div className="challengeCta"><div><b>설명만 보는 것보다 직접 해보는 편이 빠릅니다.</b><span>V2 Sandbox에서 Canvas를 작성하며 첫 Workflow를 설계해보세요.</span></div><a href="?version=2#cases" className="v3primary">전체 Sandbox 열기 <ArrowRight size={18}/></a></div></section>
<section id="weeks" className="v3weeks"><div className="v3heading"><span>딱 4주</span><h2>한 주에 한 단계씩,<br/>난이도가 올라갑니다.</h2><p>목표는 AI 전문가가 되는 것이 아니라 <strong>내 일을 AI와 함께 설계하고, 문제가 생기면 고칠 수 있는 사람</strong>이 되는 것입니다.</p></div><div className="v3weekgrid">{weeks.map(([w,h,p,I])=><article key={w}><div><b>{w}</b><I/></div><h3>{h}</h3><p>{p}</p></article>)}</div></section>
<section id="result" className="v3result"><div><span className="v3tag">4주 뒤 내 손에 남는 것</span><h2>수료증보다 먼저,<br/><em>설명할 수 있는 결과물.</em></h2><p>무엇을 자동화했는지만 보여주는 것이 아니라 <strong>왜 이렇게 설계했고, AI의 오류를 어디서 사람이 확인하는지</strong>까지 설명하는 실무 포트폴리오를 목표로 합니다.</p><small>예: 보고서 Workflow · 고객문의 분류 · 계약 검토 보조 · 시장정보 Briefing · 신사업 기회 탐색</small></div><div className="v3portfolio"><span>MY AI WORK · PORTFOLIO</span><h3>이 업무를<br/>이렇게 다시 설계했습니다.</h3><ul><li>문제: 어떤 업무가 왜 불편했는가</li><li>설계: AI와 사람이 각각 무엇을 하는가</li><li>안전: 오류·예외·민감정보를 어떻게 다루는가</li><li>검증: 조건이 바뀌어도 수정할 수 있는가</li><li>전이: 다른 업무에도 적용할 수 있는가</li></ul><b>경험 + AI + 판단 = 나만의 업무 설계</b></div></section>
<section className="v3for"><div className="v3heading"><span>이런 분이라면</span><h2>경력이 오히려 재료가 됩니다.</h2></div><div className="v3who">{who.map((x,i)=><div key={x}><b>{String(i+1).padStart(2,'0')}</b><p>{x}</p></div>)}</div><p className="v3quiet">오래 일했다는 것은 이미 수많은 예외와 판단 기준을 알고 있다는 뜻입니다.<br/><strong>그 경험을 AI가 함께 일할 수 있는 구조로 바꾸는 것</strong>이 S.T.A.크래프트의 학습 가설입니다.</p></section>
<section id="start" className="v3final"><Sparkles/><h2>첫 과제는 작게.<br/><em>마지막 과제는 깊게.</em></h2><p>가상 데이터로 시작하므로 회사 자료를 준비할 필요가 없습니다.<br/>먼저 공개된 설계 과제를 직접 경험해보세요.</p><a href="?version=2#lab" className="v3primary">무료 과제 시작하기 <ArrowRight size={18}/></a><small>현재 공개 검증용 프로토타입입니다. 정규 과정·1:1 지원·학습성과는 검증 및 준비 중입니다.</small></section></main><footer className="v3footer"><b>S.T.A.크래프트 · Landing V3.1</b><span>쉬운 시작 → 실패와 수정 → 고급 의사결정 설계</span></footer></div>}
